source 'https://github.com/CocoaPods/Specs.git'

target 'FMEventDispatcher', :exclusive => true do
  pod "FMEventDispatcher", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "FMEventDispatcher", :path => "../"

  
end
